### ISSUE TITLE
GQL Mutation requirements

### ISSUE THREAD

**Issue by jimador-sf** [Superformula/test-full-stack#1]
From the requirements, and Figma mockups, it appears that the only mutations required are `createUser` and `updateUser`. Is the delete functionality required?

**Comment by afaq-sf** [comment]
Great question.

Only behavior depicted in Figma or mentioned in the Readme is required. 

If you notice additional system-level additions that add value to the product, we would welcome them as additional bonus contributions, whether as code or just a description of how you'd go about it. We would then use it as a launching off point for discussion during the PR review.

Please let us know if that provides enough clarity.

**Comment by jimador-sf** [comment]
@afaq-sf Sounds great. I added a **_Gold-plating_** section to the kanban board I linked in the updated README
