### ISSUE TITLE
Clarification: "Infinite loading state should be saved in url query"

### ISSUE THREAD

**Issue by adam-zhu** [Superformula/test-full-stack#10]
<img width="1011" alt="Screen Shot 2020-07-08 at 3 30 35 PM" src="https://user-images.githubusercontent.com/8375624/86961904-9ff8f600-c127-11ea-9ab3-5c093cea899d.png">

Under https://github.com/Superformula/test-full-stack#functionality-1, the third item is
> "Infinite loading state should be saved in url query"

Does this mean that the source of truth for what users are displayed on the page needs to come from the URL?

**Comment by mat-sf** [comment]
>Does this mean that the source of truth for what users are displayed on the page needs to come from the URL?

Yes, and the user should be able to reload the page while still returning to their current scroll position (e.g. `?page=1`).
