### ISSUE TITLE
Question about the mock up

### ISSUE THREAD

**Issue by TommyC5** [Superformula/test-full-stack#11]
Hello

A quick question regarding the mock-up, is the intention to use those as a reference or you guys are looking for pixel-perfect implementation?  The reason I am asking is I pretty much use the mockup as a reference and decided to put in my design touches so to speak.  i.e pretty much this is what I created from scratch

![image](https://user-images.githubusercontent.com/37598904/86981092-a8672600-c153-11ea-8e63-c4a59bc8e719.png)

If you guys are looking for pixel-perfect precision, I will pretty much change gear.  

Thanks

**Comment by wprater** [comment]
@TommyC5 please stick to the Figma reference design.  Thank you!
