### ISSUE TITLE
Build/Deploy Credentials

### ISSUE THREAD

**Issue by Applicant-SF** [Superformula/test-full-stack#13]
Parts of my build and deploy pipeline require Third Party Credentials (AWS, etc). 

Will you supply your own credentials if/when you test; or should credentials be provided in the repo (this is a public repo!)?

**Comment by wprater** [comment]
We can use our own, or better yet, please instruct us on how to acquire and use a set or credentials as you would in a production or even dev app to keep them safe. 

Thanks!
