### ISSUE TITLE
Infinite loading state should be saved in url query?

### ISSUE THREAD

**Issue by LuisRevillaM** [Superformula/test-full-stack#17]
Hi!

I'm having fun with this test; now down to the UI.

I do wonder what do we mean exactly with **"Infinite loading state should be saved in url query"**.

My assumption is that we want to load more users as we scroll. Though the mockup has a **Load More** button, so I'm not entirely sure about that.

Regarding the state and the query, is it the pagination state we want to keep? 

I imagine we could store the "page" token, and use it to load every user up to that point on page refresh.

Thank you!

**Comment by marcin-piela-sf** [comment]
We want to load more users on click "Load more" button and then after refresh the page we want to see the same amount of users without clicking "Load more"

**Comment by uriel-sf** [comment]
> We want to load more users on click "Load more" button and then after refresh the page we want to see the same amount of users without clicking "Load more"

Should we update the docs. I also had the same question :-)
