### ISSUE TITLE
Figma source access request

### ISSUE THREAD

**Issue by jimador-sf** [Superformula/test-full-stack#2]
Requesting access permission to the Figma source link in the test.

**Comment by marcin-piela-sf** [comment]
@jimador-sf you should have access to it

https://www.figma.com/file/hd7EgdTxJs2fpTzzSKlNxo/Superformula-full-stack-test

Just create an account and you will be able to read/check css styles. You don't need write access to that file.

**Comment by jimador-sf** [comment]
Thank you!
