### ISSUE TITLE
UI Functionality question

### ISSUE THREAD

**Issue by jimador-sf** [Superformula/test-full-stack#3]
I am unclear on the following: 

> Infinite loading state should be saved in url query

Should this be _Infinite scroll state should be saved in url query_? Or perhaps _Current pagination state should be present in url params_?

**Comment by afaq-sf** [comment]
The intent is that the current pagination state should be present in URL query (eg ?page=1) to allow for behavior where the user can reload the page while still returning to their current scroll position.

@wprater @marcin-piela-sf Please weigh in if I'm off base here.
