### ISSUE TITLE
Tech stack clarification

### ISSUE THREAD

**Issue by nickk-sf** [Superformula/test-full-stack#37]
Before jumping in, I'd like to clarify couple of things around preferred tech stack you're expecting. While the majority of things are clearly explained, two pieces seem to be outside the scope:

1. Would you prefer Next.js over pure React?
2. Is it acceptable to use AWS Amplify to facilitate scaffolding different AWS Services needed for the job?

**Comment by marcin-piela-sf** [comment]
Hi Nick :)

1. We prefer Next.js but it's not most important in this code challenge (just choose what you would choose in a production app)

2. You're more focused on FE so yes, that will be ok
