### ISSUE TITLE
Input requirements

### ISSUE THREAD

**Issue by jimador-sf** [Superformula/test-full-stack#4]
A couple of questions for the user input requirements: 

1. What constitutes a valid user name? (Is there a client provided regex for name validation?) If not...
    - Is there a limit requirement on the number of input characters?
    - Is there a limit requirement on the number of input word groups?
    - Are there any special characters that should be excluded/included? 
         - Is `Bobby'); DROP TABLE Users;--` a valid name?
2. What constitutes a valid Location format? The GQL API indicates that it is the user address, but the UI form field is `Location`. 
3. What business rules exist around the `Description` input? 
    - Is there a max character length for that field? 
    - Are special characters allowed?

**Comment by afaq-sf** [comment]
@jimador-sf Apologies on the super late reply. Hopefully I am not providing any curve-ball answers.

> What constitutes a valid user name? (Is there a client provided regex for name validation?)
No, there is not a prescribed validation format/regex

> Is there a limit requirement on the number of input characters?
> Are there any special characters that should be excluded/included?

Please assume a hard requirement has not been set by the product owner. We welcome any input validations and your reasoning for why they add value.

> What constitutes a valid Location format?

Please assume that the product owner has asked for this to be a text field for free-entry at the very least. 
Examples:
- Seattle, Washington
- Digital Nomad
- New Jersey
- Northern Bergen County, NJ

However, any additional helper behavior on top of that would be welcomed and considered a bonus contribution.

>What business rules exist around the Description input?

Similar to #1, there is not hard-requirement provided. A simple free-text description field would be acceptable. However, we would be looking for any validations you apply and asking for reasoning / opinions on why they are applicable for this type of field.
