### ISSUE TITLE
Backend geocoding requirements

### ISSUE THREAD

**Issue by jimador-sf** [Superformula/test-full-stack#5]
The requirement: 

> Add a Query to fetch location information based off the user's address (use NASA or Mapbox APIs); use AWS Lambda

Is the requirement to implement geocoding as a Lambda or that the user address be valid? Mapbox's API supports embedding geocoding queries, so this can be directly embedded in the FE User Info Modal component. That might make for better UX, as the user can get realtime feedback from the location typeahead. It also helps to prevent a range of [post form submit] client validation issues that could arise, as we can be relatively certain that the input provided by the geocoding library is correct.

**Comment by marcin-piela-sf** [comment]
To implement geocoding as a **Lambda** - to check how you deal with it, how you connect it with GraphQL API and check if you are familiar with AWS configuration (eg. using AppSync).

Good explanation why it can be better to use it directly in FE app 👍
